import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

    <body className={inter.className}>{children}
    <script charSet="UTF-8" src="//web.webpushs.com/js/push/bf279801cedd1128580201717dd195b3_1.js" async></script>

    </body>
    </html>
  );
}
