import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

    <body className={inter.className}>{children}
    <script src="https://cdn.by.wonderpush.com/sdk/1.1/wonderpush-loader.min.js" async></script>
    <script>
      window.WonderPush = window.WonderPush || [];
      WonderPush.push(["init", {
      webKey: "c659bc5984cf8ddb1f5c0ceeab978155ab2763f7ee6ae023d57a622c36a4512c",
    }]);
    </script>

    </body>
    </html>
  );
}
