import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {SetupCmp} from "@/components/SetupCmp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

    <head>
      <script src="https://cdn.by.wonderpush.com/sdk/1.1/wonderpush-loader.min.js" async></script>
    </head>

    <body className={inter.className}>
    {children}

    <SetupCmp/>

    </body>
    </html>
  );
}
